name: "🧍Daily stand up"
title: 'Status update today'
labels: daily
body:
  - type: markdown
    attributes:
      value: |
        Time for the async standup of today 🔄
  - type: input
    attributes:
      label: How do you feel today
      description: How do you feel today?
  - type: textarea
    attributes:
      label: What will you do today?
  - type: textarea
    attributes:
      label: Anything blocking you?
  - type: textarea
    attributes:
      label: Want to get some help?
      placeholder: Mention your team mates to let them know!
